### ISSUE TITLE
Bug: Release Issue on quote plugin

### ISSUE THREAD

**Issue by poofichu** [punchcard-cms/input-plugin-quote#27]
Something funky is happening with the release for the quote input plugin.  The HTML has been updated for this plugin, but Punchcard isn't pulling in the latest for some reason.  The release number for both looks correct.
## Steps for Reproducing
- Check HTML for input-plugin-quote (which is correct)
- Check HTML for pulled in dependency in Punchcard (which is NOT correct)
- Notice they are different
- Notice version #'s are the same in `package.json`
## Affected Browsers
- All
## Runtime Version

v5.11
## Code Version

Latest

**Comment by scottnath** [comment]
@poofichu #33 should solve this bug
